### ISSUE TITLE
TurtleTrendFollow_cBot: Sequence contains no elements

### ISSUE THREAD

**Issue by GeorgeFreelanceDeveloper** [GeorgeFreelanceDeveloper/cTraderBots#42]
Prosim o provereni chyby Sequence contains no elements, ktera se objevila v logu dne 11.2.2024

Celkovy pocet vyskytu:
Chyba se objevila jen dne 11.2.2024 (nedele) opakovene behem casu 18:09 - 18:10

```log
[11.02.2024 18:09:17 - BTCUSD] INFO: Start OnBar
[11.02.2024 18:09:17 - BTCUSD] INFO: Process market: BTCUSD
[11.02.2024 18:09:17 - BTCUSD] INFO: ExecuteStrategyPerLevel: L1
[11.02.2024 18:09:17 - BTCUSD] INFO: Process market: ETHUSD
[11.02.2024 18:09:17 - BTCUSD] INFO: ExecuteStrategyPerLevel: L1
[11.02.2024 18:09:17 - BTCUSD] INFO: Process market: BNBUSD
[11.02.2024 18:09:17 - BTCUSD] INFO: ExecuteStrategyPerLevel: L1
[11.02.2024 18:09:17 - BTCUSD] ERROR: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at cAlgo.Robots.TurtleTrendFollow_cBot.ExecuteStrategyPerLevel(Level level, String market)
   at cAlgo.Robots.TurtleTrendFollow_cBot.OnBar()
   at cTrader.Automate.Adapters.RobotWrapper.OnBar()
   at cTrader.Automate.Host.Runtime.Instances.SmallRobotInstance.<.ctor>b__7_1()
   at cTrader.Automate.Host.Runtime.AlgoExecutor.SmallAlgoCodeExecutorExtensions.<>c.<.cctor>b__3_0(Action a)
   at cTrader.Automate.Domain.Shared.Dispatcher.DispatcherAction.DispatcherActionImpl`1.Invoke()
   at cTrader.Automate.Host.Runtime.AlgoExecutor.SmallAlgoCodeExecutor.ExecuteInternal(IDispatcherAction& action, Boolean raiseFrameEvent)
```

**Comment by GeorgeFreelanceDeveloper** [comment]
## Analyza

Dle logu to vypada, ze se jednalo o nejake testovaci spousteni s trhy ktere se normalne v ramci global portfolia neobchoduji (ETH a BNB)

Dale se chyba uz v logu vicekrat neobjevila v ramci global portfolia (BTCUSD, NAS100)
